
import { Provider, Doctor, Procedure } from './schema';

export const markets = {
  sources: ['Africa','SAARC','Nepal','Russia','Middle East'],
  destinations: ['India','Nepal','UAE','Russia']
};

export const providers: Provider[] = [
  {
    id: 'prov_del_heart',
    org_name: 'HealinginEast Partner · Sunrise Heart Institute',
    accreditations: ['JCI','NABH'],
    country: 'India',
    city: 'New Delhi',
    address: '123 Healthcare Ave, New Delhi',
    geo: { lat: 28.6139, lng: 77.2090 },
    verified: true,
    languages: ['English','Hindi','Arabic'],
    specialties: ['Cardiac'],
    rating: 4.7,
    reviewCount: 412,
    distanceToAirportKm: 14,
  },
  {
    id: 'prov_mum_onc',
    org_name: 'HealinginEast Partner · Lotus Oncology Center',
    accreditations: ['NABH'],
    country: 'India',
    city: 'Mumbai',
    address: '88 Wellness Rd, Mumbai',
    geo: { lat: 19.0760, lng: 72.8777 },
    verified: true,
    languages: ['English','Hindi','Marathi','Arabic'],
    specialties: ['Oncology'],
    rating: 4.5,
    reviewCount: 188,
    distanceToAirportKm: 6,
  },
  {
    id: 'prov_kath_fert',
    org_name: 'HealinginEast Partner · Kathmandu Fertility Clinic',
    accreditations: ['JCI'],
    country: 'Nepal',
    city: 'Kathmandu',
    address: 'Ring Road 12, Kathmandu',
    geo: { lat: 27.7172, lng: 85.3240 },
    verified: true,
    languages: ['English','Nepali','Hindi'],
    specialties: ['Fertility'],
    rating: 4.6,
    reviewCount: 96,
    distanceToAirportKm: 7,
  },
  {
    id: 'prov_dxb_cos',
    org_name: 'HealinginEast Partner · Dubai Aesthetics Hospital',
    accreditations: ['JCI'],
    country: 'UAE',
    city: 'Dubai',
    address: 'Sheikh Zayed Rd, Dubai',
    geo: { lat: 25.2048, lng: 55.2708 },
    verified: true,
    languages: ['English','Arabic','Russian'],
    specialties: ['Cosmetics'],
    rating: 4.6,
    reviewCount: 231,
    distanceToAirportKm: 12,
  },
  {
    id: 'prov_mow_onc',
    org_name: 'HealinginEast Partner · Moscow Oncology Center',
    accreditations: ['JCI'],
    country: 'Russia',
    city: 'Moscow',
    address: 'Leninsky Ave, Moscow',
    geo: { lat: 55.7558, lng: 37.6173 },
    verified: true,
    languages: ['Russian','English'],
    specialties: ['Oncology'],
    rating: 4.4,
    reviewCount: 142,
    distanceToAirportKm: 28,
  }
];

export const doctors: Doctor[] = [
  { id: 'doc_asha', provider_id: 'prov_del_heart', name: 'Dr. Asha Mehta', specialties: ['Cardiac'], experience_years: 18, languages: ['English','Hindi'], rating: 4.8 },
  { id: 'doc_rahul', provider_id: 'prov_mum_onc', name: 'Dr. Rahul Iyer', specialties: ['Oncology'], experience_years: 15, languages: ['English','Hindi','Marathi'], rating: 4.5 },
  { id: 'doc_kiran', provider_id: 'prov_kath_fert', name: 'Dr. Kiran Shrestha', specialties: ['Fertility'], experience_years: 12, languages: ['English','Nepali','Hindi'], rating: 4.6 },
  { id: 'doc_amina', provider_id: 'prov_dxb_cos', name: 'Dr. Amina Al-Sabah', specialties: ['Cosmetics'], experience_years: 14, languages: ['Arabic','English','Russian'], rating: 4.7 },
  { id: 'doc_ivan', provider_id: 'prov_mow_onc', name: 'Dr. Ivan Petrov', specialties: ['Oncology'], experience_years: 16, languages: ['Russian','English'], rating: 4.4 },
];

export const procedures: Procedure[] = [
  {
    id: 'proc_cabg_del',
    provider_id: 'prov_del_heart',
    name: 'Coronary Artery Bypass Grafting (CABG)',
    specialty: 'Cardiac',
    base_price: 5200,
    currency: 'USD',
    inclusions: ['Surgeon fees', 'OT & anesthesia', 'ICU (3 days)', 'Room (4 days)'],
    exclusions: ['Flights', 'Hotel', 'Post-op physiotherapy'],
    avg_LOS_days: 7,
  },
  {
    id: 'proc_chemo_mum',
    provider_id: 'prov_mum_onc',
    name: 'Chemotherapy (1 cycle)',
    specialty: 'Oncology',
    base_price: 950,
    currency: 'USD',
    inclusions: ['Drug cost', 'Day-care', 'Nursing'],
    exclusions: ['Companion meals', 'Accommodation'],
    avg_LOS_days: 1,
  },
  {
    id: 'proc_ivf_kath',
    provider_id: 'prov_kath_fert',
    name: 'IVF (one cycle)',
    specialty: 'Fertility',
    base_price: 2600,
    currency: 'USD',
    inclusions: ['Consults', 'Stimulation', 'OPU', 'ET'],
    exclusions: ['Genetic testing', 'Freezing beyond 6 months'],
    avg_LOS_days: 14,
  },
  {
    id: 'proc_rhinoplasty_dxb',
    provider_id: 'prov_dxb_cos',
    name: 'Rhinoplasty (Cosmetic nose surgery)',
    specialty: 'Cosmetics',
    base_price: 3800,
    currency: 'USD',
    inclusions: ['Surgeon & OT', '1 night stay', 'Follow-up consult'],
    exclusions: ['Flights', 'Hotel', 'Revisions beyond 1'],
    avg_LOS_days: 2,
  },
  {
    id: 'proc_targeted_mow',
    provider_id: 'prov_mow_onc',
    name: 'Targeted Therapy (per cycle)',
    specialty: 'Oncology',
    base_price: 2200,
    currency: 'USD',
    inclusions: ['Drug cost', 'Oncologist review', 'Day-care'],
    exclusions: ['Genetic panel', 'Imaging'],
    avg_LOS_days: 1,
  }
];
